/* Auto-generated by genmsg_cpp for file /home/akshay/ros_workspace/pf_drone_state_estimation/msg/Measurement_data.msg */
#ifndef PF_DRONE_STATE_ESTIMATION_MESSAGE_MEASUREMENT_DATA_H
#define PF_DRONE_STATE_ESTIMATION_MESSAGE_MEASUREMENT_DATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "pf_drone_state_estimation/Feature_msg.h"

namespace pf_drone_state_estimation
{
template <class ContainerAllocator>
struct Measurement_data_ {
  typedef Measurement_data_<ContainerAllocator> Type;

  Measurement_data_()
  : header()
  , features()
  {
  }

  Measurement_data_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , features(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::pf_drone_state_estimation::Feature_msg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::pf_drone_state_estimation::Feature_msg_<ContainerAllocator> >::other >  _features_type;
  std::vector< ::pf_drone_state_estimation::Feature_msg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::pf_drone_state_estimation::Feature_msg_<ContainerAllocator> >::other >  features;


  typedef boost::shared_ptr< ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Measurement_data
typedef  ::pf_drone_state_estimation::Measurement_data_<std::allocator<void> > Measurement_data;

typedef boost::shared_ptr< ::pf_drone_state_estimation::Measurement_data> Measurement_dataPtr;
typedef boost::shared_ptr< ::pf_drone_state_estimation::Measurement_data const> Measurement_dataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pf_drone_state_estimation

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3811ed9c9a95cff36a423c1adf3afc4c";
  }

  static const char* value(const  ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3811ed9c9a95cff3ULL;
  static const uint64_t static_value2 = 0x6a423c1adf3afc4cULL;
};

template<class ContainerAllocator>
struct DataType< ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pf_drone_state_estimation/Measurement_data";
  }

  static const char* value(const  ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
Feature_msg[] features\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: pf_drone_state_estimation/Feature_msg\n\
Header header\n\
\n\
float64 px\n\
float64 py\n\
\n\
Feature_Keypoint f\n\
\n\
float64 posX\n\
float64 posY\n\
float64 posZ\n\
\n\
================================================================================\n\
MSG: pf_drone_state_estimation/Feature_Keypoint\n\
Header header\n\
\n\
float64 x\n\
float64 y\n\
\n\
float64 size\n\
float64 angle\n\
float64 response\n\
int32 octave\n\
int32 class_id\n\
\n\
\n\
";
  }

  static const char* value(const  ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.features);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Measurement_data_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pf_drone_state_estimation::Measurement_data_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "features[]" << std::endl;
    for (size_t i = 0; i < v.features.size(); ++i)
    {
      s << indent << "  features[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::pf_drone_state_estimation::Feature_msg_<ContainerAllocator> >::stream(s, indent + "    ", v.features[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // PF_DRONE_STATE_ESTIMATION_MESSAGE_MEASUREMENT_DATA_H

